apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxer-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boxer-service
  template:
    metadata:
      labels:
        app: boxer-service
    spec:
      containers:
      - name: boxer-service
        imagePullPolicy: Never
        image: segment17/boxerservice
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boxer-service
spec:
  type: LoadBalancer
  selector:
    app: boxer-service
  ports:
    - port: 8765
      targetPort: 8080
