apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxer-service-deployment
  labels:
    app: boxer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boxer-service
  template:
    metadata:
      labels:
        app: boxer-service
    spec:
      containers:
      - name: boxer-service
        imagePullPolicy: IfNotPresent
        image: segment17hub/boxerservice:0.1
        ports:
        - containerPort: 50051
        env:
          - name: BOXER_MYSQL_SERVICE_ADDR
            value: "boxer-mysql-service"
---
apiVersion: v1
kind: Service
metadata:
  name: boxer-service
  labels:
    app: boxer-service
spec:
  type: ClusterIP
  selector:
    app: boxer-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
# MYSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxer-mysql-deployment
spec:
  selector:
    matchLabels:
      app: boxermysql
  template:
    metadata:
      labels:
        app: boxermysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
          - name: boxer-mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: boxer-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: boxer-mysql-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: boxer-mysql-service
spec:
  selector:
    app: boxermysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boxer-mysql-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: boxer-service
spec:
  grpc: True
  prefix: /ubc_package.BoxerService/
  rewrite: /ubc_package.BoxerService/
  service: boxer-service:50051
---
